spring:
  application:
    name: firstSpringBoot
  datasource:
      url: jdbc:mysql://localhost:3306/mystore?createDatabaseIfNotExist=true
      username: root
      password: P@ssword
  jpa:
    show-sql: true
  mvc:
    hidden method:
      filter:
        enabled: true

